[package]
name = "replay-mocker"
version = "0.1.0"
authors = ["Justin Miller <dragondef@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.42"
futures = "0.3.8"
hyper = "0.13.9"
serde = "1.0.118"
serde_json = "1.0.60"
bytes = "0.5"
tokio = { version = "0.2", features = ["full"] }
hyper-rustls = "0.21.0"

[dev-dependencies]
